#build stage
FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/app
COPY . .
RUN go get -d -v ./...
RUN go build -o /aamau-be -v  .

#final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /aamau-be /aamau-be
RUN mkdir /cfg
COPY  cfg/az_config.yaml /cfg/config.yaml
ENTRYPOINT /aamau-be
LABEL Name=aamau-be Version=0.0.1
EXPOSE 8080
