version: '3.4'

services:
  aamau-be:
    image: aamau
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 3305:8080

  aamau-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'ben'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'aamauDB'
    volumes:
      - aamaudbvol:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d

  aamau-db-admin:
    image: adminer
    ports:
      - 3307:8080
volumes:
  aamaudbvol:
